# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(verbose_name='2/25/16')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
